repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.7.2
    hooks:
      - id: pylint
        types: [python]
        additional_dependencies: [pylint_flask_sqlalchemy]
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
